Ed 154/feat/economic area api
rbkmoney/erlang_capi_v2 pull request #543
Opened 2021-06-15 14:43 UTC by arikai

2021-06-15 14:44 UTC, arikai commented
Sidenote: не смог понять логику разброса encode/decode функций по модулям. Для используемых в одном модуле – понятно, для остальных – пазл 🤔

2021-06-15 14:55 UTC, kpy3 requested changes

2021-06-15 14:55 UTC, kpy3 commented on apps/capi/src/capi_handler_countries.erl
> +    #domain_Country{name = Name, trade_blocs = TradeBlocsThrift} = Data,
`trade_blocs` может быть не задан, по протоколу он `optional`

2021-06-16 08:31 UTC, kpy3 requested changes

2021-06-16 10:42 UTC, kpy3 approved these changes

2021-06-16 14:03 UTC, merged